-- Core Creator Engine schema

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Content ideas generated by LLM
CREATE TABLE IF NOT EXISTS content_ideas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    idea_title TEXT NOT NULL,
    idea_topic TEXT,
    hook TEXT,
    script_short TEXT,
    script_medium TEXT,
    script_long TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Posts mapped to each platform
CREATE TABLE IF NOT EXISTS platform_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    idea_id UUID REFERENCES content_ideas(id) ON DELETE SET NULL,
    platform TEXT NOT NULL,              -- tiktok | instagram | x | linkedin
    platform_post_id TEXT,               -- remote id
    caption TEXT,
    media_url TEXT,                      -- CDN / Supabase storage URL
    posted_at TIMESTAMPTZ,
    status TEXT DEFAULT 'queued',        -- queued | posting | posted | failed
    first_comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Raw metrics pulled from each platform
CREATE TABLE IF NOT EXISTS analytics_raw (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id UUID REFERENCES platform_posts(id) ON DELETE CASCADE,
    impressions BIGINT,
    views BIGINT,
    likes BIGINT,
    comments BIGINT,
    shares BIGINT,
    saves BIGINT,
    watch_time_seconds DOUBLE PRECISION,
    completion_rate DOUBLE PRECISION,
    collected_at TIMESTAMPTZ DEFAULT NOW()
);

-- Scored + ranked performance
CREATE TABLE IF NOT EXISTS analytics_scored (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    idea_id UUID REFERENCES content_ideas(id) ON DELETE CASCADE,
    final_score DOUBLE PRECISION,
    rank INT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_posts_platform ON platform_posts(platform);
CREATE INDEX IF NOT EXISTS idx_posts_status ON platform_posts(status);
CREATE INDEX IF NOT EXISTS idx_analytics_post ON analytics_raw(post_id);
CREATE INDEX IF NOT EXISTS idx_scored_idea ON analytics_scored(idea_id);
